### ISSUE TITLE
Error: Objective Function Undefined at Initial Point

### ISSUE THREAD

**Issue by mdefende** [gkaguirrelab/transparentTrack#123]
Hi. I'm trying to run the pipeline from beginning to end on one of the videos we recorded in our setup. I was following the code written in the DEMO_eyeTracking, changing paths and such. I didn't make the specific measurements that were in that script for creating the scene geometry, so I just used the default settings instead with the calls:

sceneGeometry = createSceneGeomtry():
[cameraDepth, cameraDepthSD] = depthFromIrisDiameter(sceneGeometry,maxIrisDiamPixels);

The pipeline runs very well up until the estimateSceneParams call where the error Objective Function Undefined at Initial Point is thrown. I'm including a screenshot of the entire error output for more information. 

![estimatesceneparams_error](https://user-images.githubusercontent.com/20781527/41378211-fb4cdb28-6f23-11e8-8d1b-326a9d01e60d.png)

I can upload the eyetracking video file if that would help, but I was wondering if this error may be due to just using the defaults for creating the scene geometry or if there is something else I am missing. Thanks

**Comment by mdefende** [comment]
Also, I'm using the most recent version of the toolbox from the TbTb registry. I deleted and redownloaded it today. Let me know what other information would be helpful with this. Thanks!

**Comment by gkaguirre** [comment]
Matt -- Thanks for posting this. Let me take a look. As I'm sure you've seen, the code has been undergoing some heavy revision in recent weeks. I have not properly tested the scene Geometry estimation routines since I split off the model eye code. I'll run through the demo for this in the next day or so and let you know what I find.

**Comment by gkaguirre** [comment]
Matt -- I just ran the `DEMO_eyeTracking.m` routine from the start through the estimateSceneParams stage. It ran without errors, which raises the possibility that the values you are passing for `sceneParamsUB/LB/UBp/LBp` are defective in some way. I propose that you put a breakpoint stop on line 165 of the estimateSceneParams.m routine and then run the analysis on your video (perhaps skipping steps 1-6 to save time). Once you hit that breakpoint, please inspect the values for p.Results.sceneParamsLB, etc, and post them here.

**Comment by mdefende** [comment]
p.Results.sceneParamsLB = [-30, -20, -20, 90, 0.75, 0.9];
p.Results.sceneParamsLBp = [-15, -5, -5, 100, 0.85, 0.95];
p.Results.sceneParamsUBp = [15, 5, 5, 160, 1.15, 1.05];
p.Results.sceneParamsUB = [30, 20, 20, 200, 1.25, 1.1];

I'm not setting these values outside of the estimateSceneParams function since I'm not familiar with what the values mean physically and what numbers would be appropriate so I just went with the defaults since it seemed like they were a large enough range to cover our setup.

**Comment by gkaguirre** [comment]
Thanks. Could you post as well one still frame from the video?

--

Geoffrey Karl Aguirre, MD, PhD
https://cfn.upenn.edu/aguirre
Associate Professor of Neurology
University of Pennsylvania

**Comment by mdefende** [comment]
![mdp001_ret01_frame1](https://user-images.githubusercontent.com/20781527/41478588-e97d4e76-708d-11e8-9c18-a0c0d5d1fef1.png)

![mdp014_gazecal01_frame1](https://user-images.githubusercontent.com/20781527/41478537-a59b438e-708d-11e8-8970-6debdb178d70.png)

It happens in both of these videos. I haven't had time to try it on the rest of the videos I have yet, unfortunately.

**Comment by gkaguirre** [comment]
Could you please post the `_pupil.mat` file for one of the subjects that is crashing at the estimate scene parameters step? I'll take a look and see if it is having trouble selecting appropriate ellipses to guide the search.

**Comment by mdefende** [comment]
[MDP014_GazeCal01_pupil.mat.zip](https://github.com/gkaguirrelab/transparentTrack/files/2108479/MDP014_GazeCal01_pupil.mat.zip)

I've attached the pupil file for MDP014 as a zip file since GitHub doesn't allow attachment of .mat files apparently.
