### ISSUE TITLE
Invalid eyePose value

### ISSUE THREAD

**Issue by mdefende** [gkaguirrelab/transparentTrack#128]
Hi,

I have been running a video through the pipeline and have made it past the scene parameter estimation step, but am getting an error in the second fitPupilPerimeter step near the end of the Bayesian smoothing. I'm including a picture with the error. Let me know what other files I should send. Thanks!

![mdp014_smoothpupilradius_error](https://user-images.githubusercontent.com/20781527/41688819-3d5cfb12-74b3-11e8-8460-7ded58c5375c.PNG)

**Comment by gkaguirre** [comment]
Please post the _pupil.mat file and I’ll take a look.

**Comment by mdefende** [comment]
[MDP014_GazeCal01_pupil.zip](https://github.com/gkaguirrelab/transparentTrack/files/2121658/MDP014_GazeCal01_pupil.zip)

**Comment by gkaguirre** [comment]
Sorry, I need the perimeter and sceneGeometry files as well.

**Comment by mdefende** [comment]
No problem, here you go! 
[MDP014_GazeCal01_Files.zip](https://github.com/gkaguirrelab/transparentTrack/files/2121863/MDP014_GazeCal01_Files.zip)

**Comment by gkaguirre** [comment]
Matt -- I replicated the error and have pushed a fix. Code has been updated in both the `transparentTrack` and `gkaModelEye` repos. There was one frame of the video, during a blink, for which the attempt to fit an ellipse to the pupil failed (appropriately so), but in a way that the code had not anticipated.
