### ISSUE TITLE
Unable to use estimateSceneParamsGUI, Creating Poor Fit when Using estimateSceneParams

### ISSUE THREAD

**Issue by cbain00** [gkaguirrelab/transparentTrack#157]
I am currently attempting to use the estimateSceneParamsGUI on my own IR video of an eye. I would like to mention I do not have access to the camera's intrinsic matrix and have been using the same matrix from DEMO_eyeTracking at the moment.

The code is currently erroring at line 140 of estimateSceneParamsGUI where it attempts to display the frame to be analyzed, it is shown below:

```
Error using  * 
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of rows in
the second matrix. To perform elementwise multiplication, use '.*'.

Error in projectToImagePlane (line 58)
projectionMatrix = sceneGeometry.cameraIntrinsic.matrix * cameraExtrinsicMatrix;

Error in projectModelEye (line 289)
    projectToImagePlane(worldPoints,sceneGeometry);

Error in eyePoseEllipseFit (line 256)
    [~, probeCoord0] = projectModelEye(refPose, sceneGeometry, 'cameraTrans', [0;0;0]);

Error in estimateSceneParamsGUI (line 140)
    [eyePose, cameraTrans] = eyePoseEllipseFit(Xp, Yp, glintCoord,
    adjustedSceneGeometry,'eyePoseUB',[89,89,0,5],'cameraTransBounds',p.Results.cameraTransBounds);

Error in jorgeright_transparentTrack (line 107)
sceneObjects = estimateSceneParamsGUI('', 'frameSet', frameSet, 'eyeArgs', eyeArgs, 'sceneArgs', sceneArgs);
```

This error seems to be occurring since `sceneGeometry.cameraIntrinsic.matrix` is empty. However, I do not seem to have control in when this scene geometry file is created or when the intrinsic matrix is created. Is there something I'm missing?

I tried working around this error by just using estimateSceneParams instead with pre-made variables from the demo, however, this produces a poor fit as this data is not meant for my video specifically.

**Comment by gkaguirre** [comment]
It might be the case that the dimensions of your video images are different from the dimensions assigned in the intrinsic camera matrix and cameraResolution. These values are assigned and stored in the initial call to createSceneGeometry. You can assign the these values by setting and passing appropriate key-value pairs. Take a look at the header comments of the function createSceneGeometry in the repo gkaModelEye. Note that one pair of values in the intrinsic camera matrix is simply the midpoint of the sensor dimensions specified jn cameraResolution.
