### ISSUE TITLE
harmonize convertRawToGray

### ISSUE THREAD

**Issue by gkaguirre** [gkaguirrelab/transparentTrack#42]
This routine currently calls the two functions deinterlaceVideo and resizeAndCropVideo. Ideally, these three separate pieces of code should be integrated into a single routine (with integrated parameters) that is used for video pre-processing. The routine (called perhaps preprocessVideo) could offer options to deinterlace, crop, rotate, etc.

**Comment by gfrazzetta** [comment]
Done  with https://github.com/gkaguirrelab/transparentTrack/pull/47
